shoppad/mesa-templates

- shopify/orders/send-to-google-sheets/README.md
- shopify/orders/send-to-google-sheets/in-orders-google-sheets.js
- shopify/orders/send-to-google-sheets/mesa.json
- shopify/orders/send-to-google-sheets/out-orders-google-sheets.js
- Sync orders to Google Sheets on order creation.
> Shopify Orders to Google Sheets

- google-sheets/products/update-titles-on-shopify-products/README.md
- google-sheets/products/update-titles-on-shopify-products/mesa.json
- shopify/customers/send-to-google-sheets/README.md
- shopify/customers/send-to-google-sheets/mesa.json
- shopify/orders/send-to-google-sheets/mesa.json
- Updating URLs from `mesa-recipes` to `mesa-templates`
> Google sheets/fixing urls

- shopify/product/add-image-colors-to-product-as-tags/out-update-shopify-product.js
This PR fixes an issue with all tags been removed when this template gets executed.
Readme
mesa.json
Template code
QA
> Product Images Tags: Fixing issue tags getting remove

- shopify/product/add-image-colors-to-product-as-tags/out-update-shopify-product.js
There is a chance the user is using multiple automation and the tags information might be outdated. This PR adds back the Shopify call to get the most updated tags.
Readme
mesa.json
Template code
QA
> Product Images Tags: Getting tags from the Shopify API

- shopify/order/send-uploadery-file-to-dropbox/README.md
Readme
mesa.json
Template code
QA
> Update Dropbox readme

- shopify/draft-order/send-to-hubspot-deal/README.md
- shopify/draft-order/send-to-hubspot-deal/mesa.json
- shopify/draft-order/send-to-hubspot-deal/out-create-hubspot-deal.js
- shopify/order/send-to-hubspot-deal/README.md
- shopify/order/send-to-hubspot-deal/mesa.json
- shopify/order/send-to-hubspot-deal/out-create-hubspot-deal.js
- shopify/product/add-image-colors-to-product-as-tags/mesa.json
Readme
mesa.json
Template code
QA
> Hubspot templates: Update keys

- shopify/product/add-image-colors-to-product-as-tags/mesa.json
Readme
mesa.json
Template code
QA
> Add video to add-image-colors-to-product-as-tag

- shopify/draft-order/remove-after-thirty-days/README.md
- shopify/draft-order/send-email-notification/README.md
- shopify/order/add-currency-to-order-tags/README.md
- shopify/order/add-currency-to-order-tags/mesa.json
- shopify/order/add-destination-forecast-to-order-notes/README.md
- shopify/order/add-payment-gateway-tag/README.md
- shopify/order/add-shipping-province-tag/README.md
- shopify/order/add-shipping-province-tag/mesa.json
- shopify/order/send-fulfillment-issue-to-slack-channel/README.md
- shopify/order/send-fulfillment-issue-to-slack-channel/mesa.json
- shopify/order/send-to-another-store/README.md
- shopify/order/send-to-another-store/mesa.json
- shopify/order/send-uploadery-file-to-cloudinary-transform/README.md
- shopify/product/add-color-tag/README.md
- shopify/product/add-color-tag/mesa.json
- shopify/product/add-color-tag/out-add-shopify-product-tag.js
- shopify/product/add-image-colors-to-product-as-tags/README.md
Readme
mesa.json
Template code
QA
> Mandy Template Audit

- shopify/article/send-to-another-store/README.md
- shopify/article/send-to-another-store/out-create-shopify-article.js
Readme
mesa.json
Template code
QA
> Send Blog Article to Another Store: Optional URL customization

- shopify/order/send-fulfillment-issue-to-slack-channel/README.md
- shopify/order/send-order-paid-message-to-slack/README.md
- shopify/order/send-order-paid-message-to-slack/in-shopify-order-webhook.js
- shopify/order/send-order-paid-message-to-slack/mesa.json
- shopify/order/send-order-paid-message-to-slack/out-send-slack-notification.js
Readme
mesa.json
Template code
QA
> Send Order Paid Message To Slack Channel

- shopify/customer/tag-customers-with-edu-email/README.md
- shopify/customer/tag-customers-with-edu-email/in-shopify-customer-create.js
- shopify/customer/tag-customers-with-edu-email/in-shopify-customer-update.js
- shopify/customer/tag-customers-with-edu-email/mesa.json
- shopify/customer/tag-customers-with-edu-email/out-shopify-customer-update.js
Readme
mesa.json
Template code
QA
> Tag customers with edu email

- shopify/order/send-email-notification-when-order-has-notes/README.md
- shopify/order/send-email-notification-when-order-has-notes/in-shopify-order-webhook.js
- shopify/order/send-email-notification-when-order-has-notes/mesa.json
- shopify/order/send-email-notification-when-order-has-notes/out-send-email-notification-with-order-notes.js
Readme
mesa.json
Template code
QA
> Send Email Notification To Store Owner When Shopify Order Has Notes

- shopify/product/send-to-another-store/out-create-shopify-product.js
Readme
mesa.json
Template code
QA
> Send Product To Another Store: fix product create

- shopify/order/add-line-item-properties-to-notes/mesa.json
Readme
mesa.json
Template code
QA
> add-line-item-properties-to-notes2

- shopify/customer/send-to-salesforce-contact/mesa.json
- shopify/order/send-to-salesforce-contact/mesa.json
- shopify/order/send-to-salesforce-lead/mesa.json
- shopify/order/send-to-salesforce-opportunity/mesa.json
Readme
mesa.json
Template code
QA
> Salesforce templates: update source

- tests/shopify-product-created-to-shopify-update-product/README.md
- tests/shopify-product-created-to-shopify-update-product/mesa.json
- tests/shopify-product-created-to-shopify-update-product/transform.js
Readme
mesa.json
Template code
QA
> Test: Shopify Product Created to Shopify Update Product

- tests/shopify-order-created-to-email/README.md
- tests/shopify-order-created-to-email/ftp-transform.js
- tests/shopify-order-created-to-email/mesa.json
- tests/shopify-order-created-to-email/shopify-update-order-transform.js
- tests/shopify-order-created-to-email/transform-1.js
- tests/shopify-order-created-to-email/transform.js
Readme
mesa.json
Template code
QA
> Test: Shopify Order to Email

- shopify/draft-order/remove-after-thirty-days/mesa.json
- shopify/order/send-fulfillment-issue-to-slack-channel/README.md
- shopify/order/send-fulfillment-issue-to-slack-channel/mesa.json
- shopify/order/send-to-spa-ftp-file/mesa.json
Readme
mesa.json
Template code
QA
> Change date tokens to be double brackets

- infiniteoptions/order/add-infintite-options-line-items-to-google-sheet/README.md
- shopify/order/add-customers-orders-to-notes/filter.js
- shopify/order/add-customers-orders-to-notes/mesa.json
- shopify/order/add-customers-orders-to-notes/transform.js
- shopify/order/send-international-orders-to-slack/README.md
- shopify/order/send-international-orders-to-slack/filter.js
- shopify/order/send-international-orders-to-slack/mesa.json
- shopify/order/send-order-paid-message-to-slack/README.md
- uploadery/order/files-to-google-drive/README.md
- uploadery/order/send-email/README.md
Readme
mesa.json
Template code
QA
> Mesa: Filter templates

- shopify/order/send-email-notification-when-order-has-notes/out-send-email-notification-with-order-notes.js
Readme
mesa.json
Template code
QA
> Adding fourth email parameter in Mesa.email.send function

- pagestudio/page/README.md
- pagestudio/page/mesa.json
- pagestudio/page/shopify-create-order-transform.js
Readme
mesa.json
Template code
QA
> Send Page Studio Page to Another Store

- recharge/order/send-renewal-to-google-analytics/README.md
- recharge/order/send-renewal-to-google-analytics/mesa.json
- recharge/order/send-renewal-to-google-analytics/transform.js
Readme
mesa.json
Template code
QA
> Template: Recharge - Send renewal to Google Analytics

- shopify/order/flag-order-risk-if-no-price/README.md
- shopify/order/flag-order-risk-if-no-price/filter.js
- shopify/order/flag-order-risk-if-no-price/mesa.json
- shopify/order/flag-order-risk-if-no-price/transform-order.js
Readme
mesa.json
Template code
QA
> Order risk if no order price

- recharge/order/send-renewal-to-google-analytics/mesa.json
- shopify/order/flag-order-risk-if-no-price/mesa.json
Readme
mesa.json
Template code
QA
> Fixing template keys

- pagestudio/page/send-to-another-store/README.md
- tracktor/order/email-when-package-takes-too-long/README.md
- tracktor/order/email-when-package-takes-too-long/filter.js
- tracktor/order/email-when-package-takes-too-long/mesa.json
Readme
mesa.json
Template code
QA
> Tracktor: takes too long automation

- shopify/product/send-to-another-store/out-delete-shopify-product.js
- shopify/product/send-to-another-store/out-update-shopify-product.js
Readme
mesa.json
Template code
QA
> Send product to another sotre: Add check for product ID

- shopify/product/scheduled-product-price-change/README.md
- shopify/product/scheduled-product-price-change/get-products-json.js
- shopify/product/scheduled-product-price-change/mesa.json
- shopify/product/scheduled-product-price-change/update-product-transform.js
Readme
mesa.json
Template code
QA
> Scheduled Product Price Change

- shopify/product/send-to-another-store/mesa.json
Readme
mesa.json
Template code
QA
> Fixing bad script name

- tests/package-test/mesa-collection.json
- tests/package-test/shopify-order-created-to-email/README.md
- tests/package-test/shopify-order-created-to-email/ftp-transform.js
- tests/package-test/shopify-order-created-to-email/mesa.json
- tests/package-test/shopify-order-created-to-email/shopify-update-order-transform.js
- tests/package-test/shopify-order-created-to-email/transform-1.js
- tests/package-test/shopify-order-created-to-email/transform.js
- tests/package-test/shopify_tokens/mesa.json
- tests/package-test/shopify_tokens/shopify_update_customer_transform.js
Readme
mesa.json
Template code
QA
> Adding pacakge-test template

- shopify/order/send-to-shipstation/README.md
- shopify/order/send-to-shipstation/config.yml
- shopify/order/send-to-shipstation/mesa.json
- shopify/order/send-to-shipstation/shipstation_order_1_transform.js
- shopify/order/send-to-shipstation/shopify_order_1_transform.js
- shopify/order/send-to-shipstation/shopify_order_fulfillment_transform.js
- shopify/order/send-to-shipstation/transform.js
- shopify/order/send-to-shipstation/transform_1.js
- shopify/order/send-to-shipstation/transform_2.js
- shopify/order/send-to-shipstation/transform_3.js
- shopify/order/send-to-shipstation/transform_4.js
- shopify/order/update-shipstation-order/README.md
- shopify/order/update-shipstation-order/mesa.json
- shopify/order/update-shipstation-order/shipstation_customer_transform.js
- shopify/order/update-shipstation-order/shipstation_customer_transform_1.js
- shopify/order/update-shipstation-order/shipstation_order_1_transform.js
- shopify/order/update-shipstation-order/transform.js
Readme
mesa.json
Template code
QA
> ShipStation Order Create

- shopify/order/send-to-salesforce-opportunity-collection/README.md
- shopify/order/send-to-salesforce-opportunity-collection/mesa-collection.json
Readme
mesa.json
Template code
QA
> Update Salesforce collection metadata

- shopify/order/send-to-salesforce-opportunity-collection/mesa-collection.json
Readme
mesa.json
Template code
QA
> Salesforce automation - update path in collection

- shopify/order/send-to-salesforce-opportunity-collection/mesa-collection.json
Readme
mesa.json
Template code
QA
> Salesforce Opportunity Collection: Rename title

- shopify/order/update_tracktor_status_when_order_tag_added/README.md
- shopify/order/update_tracktor_status_when_order_tag_added/filter.js
- shopify/order/update_tracktor_status_when_order_tag_added/filter_1.js
- shopify/order/update_tracktor_status_when_order_tag_added/mesa.json
- shopify/order/update_tracktor_status_when_order_tag_added/transform.js
- tracktor/fulfillment/delay_in_transit_email/filter.js
- tracktor/fulfillment/delay_in_transit_email/mesa.json
- tracktor/fulfillment/delay_in_transit_email/shopify_order_transform.js
- tracktor/fulfillment/detay_in_transit_sms/README.md
- tracktor/fulfillment/detay_in_transit_sms/filter.js
- tracktor/fulfillment/detay_in_transit_sms/mesa.json
- tracktor/fulfillment/detay_in_transit_sms/shopify_order_transform.js
Readme
mesa.json
Template code
QA
> Tracktor: add additional templates for integrations page

- shopify/order/send-to-salesforce-opportunity-collection/mesa-collection.json
Readme
mesa.json
Template code
QA
> Mesa: Template collection: fix icon

- tracktor/fulfillment/delay_in_transit_email/mesa.json
- tracktor/fulfillment/delay_in_transit_sms/mesa.json
- tracktor/order/email-when-package-takes-too-long/mesa.json
Readme
mesa.json
Template code
QA
> Add Tracktor to template titles so they show up in searches

- bold/subscription/send-notification-on-new-subscription/README.md
- bold/subscription/send-notification-on-new-subscription/mesa.json
- bold/subscription/send-notification-on-subscription-product-change/README.md
- bold/subscription/send-notification-on-subscription-product-change/mesa.json
- bold/subscription/send-notification-on-subscription-product-change/transform.js
Readme
mesa.json
Template code
QA
> Bold Subscriptions: notification templates

- tracktor/fulfillment/delay_in_transit_email/mesa.json
- tracktor/fulfillment/delay_in_transit_sms/mesa.json
- tracktor/order/email-when-package-takes-too-long/mesa.json
Readme
mesa.json
Template code
QA
> Fix tokens for tracktor templates with delays

- tracktor/order/email-when-package-takes-too-long/mesa.json
…
Readme
mesa.json
Template code
QA
> Fix template:Email Customers After 20 days if their Tracktor Package has not been Delivered

- tracktor/fulfillment/delay_in_transit_email/mesa.json
- tracktor/fulfillment/delay_in_transit_sms/mesa.json
- tracktor/order/email-when-package-takes-too-long/mesa.json
Readme
mesa.json
Template code
QA
> Addl fixes to tracktor templates

- tracktor/fulfillment/delay_in_transit_email/mesa.json
Readme
mesa.json
Template code
QA
> Tracktor: Delayed email notification: Fix carrier tokens

- shopify/order/send-email-to-loyaltylion-customer-if-rewards-not-used/README.md
- shopify/order/send-email-to-loyaltylion-customer-if-rewards-not-used/mesa.json
Readme
mesa.json
Template code
QA
> LoyaltyLion: template send email

- delighted/survey/tag-shopify-customer-if-low-delighted-survey-score/README.md
- delighted/survey/tag-shopify-customer-if-low-delighted-survey-score/mesa.json
Readme
mesa.json
Template code
QA
> Delighted: tag customer

- shopify/checkout/send_sms_for_abandoned_checkout/mesa.json
- shopify/customer/tag_vip_customers/mesa.json
- shopify/order/add_loyaltylion_points/mesa.json
- shopify/order/cancel_and_restock_high_risk_orders/mesa.json
- shopify/order/send_expedited_shipping_alert_to_logistics/filter.js
- shopify/order/send_expedited_shipping_alert_to_logistics/mesa.json
- shopify/order/send_tax_receipt_for_charitable_donations/README.md
- shopify/order/send_tax_receipt_for_charitable_donations/mesa.json
- shopify/order/subscribe_shoppers_to_klaviyo_list/mesa.json
- shopify/order/tag_multiple_unfulfilled_orders_from_same_customer/filter.js
- shopify/order/tag_multiple_unfulfilled_orders_from_same_customer/filter_1.js
- shopify/order/tag_multiple_unfulfilled_orders_from_same_customer/mesa.json
- shopify/order/tag_multiple_unfulfilled_orders_from_same_customer/shopify_order_2_transform.js
- shopify/order/tag_multiple_unfulfilled_orders_from_same_customer/shopify_order_3_transform.js
- shopify/product/send_email_when_product_goes_out_of_stock/mesa.json
- tracktor/order/send_sms_when_order_delivered/mesa.json
Readme
mesa.json
Template code
QA
> Bfcm solutions

- shopify/order/send_tax_receipt_for_charitable_donations/README.md
- shopify/order/send_tax_receipt_for_charitable_donations/mesa.json
Readme
mesa.json
Template code
QA
> Tax receipt template: Clean up readme steps

- shopify/order/edit_add_product/mesa.json
Readme
mesa.json
Template code
QA
> shopify/order/edit_add_product template: Change custom to shopify

- infiniteoptions/order/update-tracktor-status/README.md
- infiniteoptions/order/update-tracktor-status/mesa.json
Readme
mesa.json
Template code
QA
> Update Tracktor status on Infinite Options order create

- tracktor/fulfillment/delay_in_transit_email/mesa.json
Readme
mesa.json
Template code
QA
> Removing Filter.js

- shopify/customer/send-to-odoo-contact/mesa.json
- shopify/order/send-to-odoo-order-collection/README.md
- shopify/order/send-to-odoo-order-collection/mesa-collection.json
- shopify/order/send-to-odoo-order/mesa.json
- shopify/order/send-to-odoo-order/transformmapping.js
https://docs.google.com/document/d/1Hnd_VaEv_nh9izHpDK5HvqykGCJfm1wsYblqlQs4lmM/edit#heading=h.9zqrmy4um1nb
Readme
mesa.json
Template code
QA
> Odoo templates

- shopify/order/send_thanks_io_postcard/mesa.json
Readme
mesa.json
Template code
QA
> Shopify Order to Thanks.io - update trigger creation

- uploadery/order/send_file_to_dropbox/mesa.json
- uploadery/order/send_file_to_google_drive/mesa.json
Readme
mesa.json
Template code
QA
> Clean up uploadery templates

- shopify/order/add_line_item_properties_to_notes/mesa.json
Readme
mesa.json
Template code
QA
> Add Line Item Properties to Order Notes Fix

- shopify/customer/send_to_omnisend_contact/mesa.json
Readme
mesa.json
Template code
QA
> Omnisend: Add customer to contact template

- returnly/send_authorized_return_to_slack_channel/mesa.json
Readme
mesa.json
Template code
QA
> Returnly: Send Authorized Return To Slack Channel

- uploadery/order/add_line_items_to_google_sheet/mesa.json
Readme
mesa.json
Template code
QA
> Uploadery to google sheets: Clean up tokens

- uploadery/order/add_line_items_to_airtable/README.md
- uploadery/order/add_line_items_to_airtable/mesa.json
Readme
mesa.json
Template code
QA
> Add uploadery/order/add_line_items_to_airtable template

- form/contact_form/mesa.json
- form/customer_dob/README.md
- form/customer_dob/mesa.json
- form/shopify_order_return/README.md
- form/shopify_order_return/mesa.json
Readme
mesa.json
Template code
QA
> Adding mesa forms

- returnly/send_to_slack/mesa.json
- shopify/customer/add_email_to_klaviyo_list/mesa.json
- shopify/customer/add_email_to_klaviyo_list_with_tag/mesa.json
- shopify/product/send_slack_message_inventory_low/mesa.json
Instructions
- Create a Klaviyo Credential if you have not done so already.
- Select or create your Klaviyo list within the Klaviyo Subscribe List Action. 
Readme
mesa.json
Template code
QA
> Adding add_email_to_klaviyo_list_with_tag template

- tracktor/order/send_email_to_customer_when_package_is_in_transit/mesa.json
- tracktor/order/send_email_when_in_transit/mesa.json
Readme
mesa.json
Template code
QA
> Adding send_email_to_customer_when_package_is_in_transit template

- shopify/theme/schedule_change/mesa.json
- shopify/theme/schedule_theme_change/mesa.json
Readme
mesa.json
Template code
QA
> Schedule Theme Change

- shopify/customer/shopify_customer_created_to_mailchimp/mesa.json
Readme
mesa.json
Template code
QA
> Adding add_email_to_mailchimp_list template

- shopify/order/send_to_delighted_nps_survey/mesa.json
Readme
mesa.json
Template code
QA
> Adding send_to_delighted_nps_survey template

- stamped_io/review/send_negative_review_to_customer_email/mesa.json
Asana task: https://app.asana.com/0/1199933048569373/1200087630934704
Readme
mesa.json
Template code
QA
- Domain = Store Hash
- Username = API Key Public
- Password = API Key Private
> Stamped.io: Negative review to customer email template

- shopify/product/send_to_salesforce_product_and_pricebook_entry/salesforce_create_pricebook_entry_transform.js
Readme
mesa.json
Template code
QA
> Salesforce: fix errant comment in pricebookentry mapping

- shopify/draft_order/remove_after_thirty_days/mesa.json
- shopify/draft_order/remove_after_thirty_days/out_shopify_draft_order_vo.js
- shopify/flow/send_to_cognito_verification/mesa.json
- shopify/order/send_fulfillment_issue_to_slack_channel/mesa.json
- shopify/order/send_fulfillment_issue_to_slack_channel/out_orders_virtual_output.js
- shopify/order/send_to_cognito_verification/mesa.json
- shopify/order/send_to_cognito_verification/out_cognito_virtual_output.js
- shopify/order/send_to_fosdick_fulfillment/mesa.json
- shopify/order/send_to_fosdick_fulfillment/out_create_fosdick_order.js
- shopify/order/send_to_spa_ftp_file/mesa.json
- shopify/order/send_to_spa_ftp_file/out_orders_vo.js
https://github.com/shoppad/ShopPad/pull/6798
Spot check / test?:
Readme
mesa.json
Template code
QA
> Updating templates to use non-script based virtual outputs

- shopify/order/send_postcard_to_customer_if_first_order/mesa.json
PostcardMania login in 1pass
Readme
mesa.json
Template code
QA
> Send a Postcard When a Customer Places Their First Order

- tracktor/order/update_status_shipping_method/mesa.json
Instructions
Readme
mesa.json
Template code
QA
> Adding update_status_shipping_method template

- yotpoloyalty/customer_points/sent_to_omnisend_contact/mesa.json
Readme
mesa.json
Template code
QA
Notes: 
- Our Yotpo Loyalty account can be accessed via the `Loyalty & Referrals by Yotpo` app listed on https://dev-mesa.myshopify.com/apps
- QA this with the live Mesa app
> Yotpo Loyalty Points Earned to Update Omnisend Contact template

- shopify/order/add_free_product_when_customer_tagged/mesa.json
Readme
mesa.json
Template code
QA
- If you have a hard time finding the Shopify Variant ID:
> Add shopify/order/add_free_product_when_customer_tagged template

- shopify/order/send_to_fosdick_fulfillment/out_create_fosdick_order.js
Fixes some issues with "non-standard" ?? fosdick payment types.
Readme
mesa.json
Template code
QA
> Fosdick template: account for paypal sourced payments

- shopify/order/send_high_risk_orders_to_sms/mesa.json
Language: https://app.asana.com/0/1199933048569373/1200468712958411
Readme
mesa.json
Template code
QA
> Send an SMS Message if a Customer Places a Fraudulent Order

- shopify/flow/send_to_custom_code/mesa.json
Language and install instructions: https://app.asana.com/0/1199933048569373/1200387078445663
Readme
mesa.json
Template code
QA
> Trigger custom code from a Shopify Flow workflow

- tiktok/reports/report/send_daily_adgroup_summary_report/mesa.json
- tiktok/reports/send_daily_adgroup_summary_report/mesa.json
Note:
This should be tested on dev version of mesa. Due to data limitations, you'll need to do the following:
Readme
mesa.json
Template code
QA
> Send daily TikTok Ad Group summary report to Google Sheets

- shopify/product/create_facebook_product/mesa.json
Readme
mesa.json
Template code
QA
> Create a Facebook product when tagged Shopify product is created

- shopify/order/send_to_google_sheets_document/README.md
- shopify/order/send_to_google_sheets_document/custom.js
- shopify/order/send_to_google_sheets_document/mesa.json
QA Steps:
Readme
mesa.json
Template code
QA
> Updating Send Order to Google Sheet Document

- shopify/order/send_to_google_sheets_document/mesa.json
Readme
mesa.json
Template code
QA
> Fixing fields in Shopify to Google Sheets workflow

- infiniteoptions/order/send_discord_message/mesa.json
- infiniteoptions/order/send_email/mesa.json
- infiniteoptions/order/send_slack_notification/mesa.json
Readme
mesa.json
Template code
QA
> Fixing wording in titles, description

- infiniteoptions/order/send_discord_message/mesa.json
- infiniteoptions/order/send_slack_notification/mesa.json
Readme
mesa.json
Template code
QA
> Changing companys to companies

- form/wholesale_application/mesa.json
QA Steps
Readme
mesa.json
Template code
QA
> Adding Wholesale Application Forms template

- form/post_purchase_survey/mesa.json
QA Instructions
Readme
mesa.json
Template code
QA
> Add form/post_purchase_survey template

- form/customer_dob/README.md
- form/customer_dob/mesa.json
Readme
mesa.json
Template code
QA
> Customer DOB forms template: add customer ID hidden field

- form/start_return_with_gorgias_ticket/mesa.json
Readme
mesa.json
Template code
QA
> Adding Mesa Forms Gorgias Ticket workflow

- form/yotpo_loyalty_customer_dob/mesa.json
Readme
mesa.json
Template code
QA
`<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">`
``
```
<style>
#mesa-form {
margin-top: 25px;
padding: 1.1428571429em;
border: 1px solid #D9D9D9;
border-radius: 4px;
margin-bottom: -20px;
}
#mesa-form button #submit {
border-color: #D9D9D9; 
}
</style>
```
> Adding Save a Customer's Date of Birth to a Yotpo Loyalty Customer template

- form/send_to_gatsby/mesa.json
Prismic language + readme: https://app.asana.com/0/1199933048569373/1200688597194329
Readme
mesa.json
Template code
QA
> Add template: form/send_to_gatsby

- shopify/product/add_placeholder_image/mesa.json
Readme
mesa.json
Template code
QA
> Add_Placeholder_Image

- shopify/product/send_digital_download/mesa.json
Readme
mesa.json
Template code
QA
> Send digital download

- infiniteoptions/order/send_email/mesa.json
Readme
mesa.json
Template code
QA
> Send Email when IO product purchased: updated description

- infiniteoptions/order/add_line_items_to_airtable/mesa.json
Readme
mesa.json
Template code
QA
> Add infiniteoptions/order/add_line_items_to_airtable template

- shopify/order/add_free_product_to_new_customer_first_order/mesa.json
- shopify/order/edit_add_product/mesa.json
Docs updates
Readme
mesa.json
Template code
QA
> Add 100% discounts for "add free product" templates

- shopify/order/send_to_google_sheets_document/mesa.json
…
Update doc: https://docs.getmesa.com/article/1316-send-order-to-google-sheets-document
Readme
mesa.json
Template code
QA
> Google Sheets UI updates: shopify/order/send_to_google_sheets_document template

- shopify/order/send_to_google_sheets_document/mesa.json
Reverts shoppad/mesa-templates#294 - Ash is reviewing the template install steps
> Revert "Google Sheets UI updates: shopify/order/send_to_google_sheets_document template"

- shopify/order/send_to_google_sheets_document/mesa.json
Reverts shoppad/mesa-templates#295
> Repush: Google Sheets UI updates: shopify/order/send_to_google_sheets_document template

- infiniteoptions/order/add_line_items_to_google_sheet/mesa.json
- shopify/order/send_to_google_sheets_document/mesa.json
- uploadery/order/add_line_items_to_google_sheet/mesa.json
Readme
mesa.json
Template code
QA
> Minor tweaks to googlesheets templates to support new create button

- form/customer_dob/mesa.json
Update name to match with MESA dashboard, enabled to `false` since this requires setup, and logging to `true`.
Readme
mesa.json
Template code
QA
> Update Save a customer's birthday to notes template

- form/post_purchase_survey/mesa.json
- form/wholesale_application/mesa.json
- infiniteoptions/order/add_line_items_to_google_sheet/mesa.json
- infiniteoptions/order/add_product_bundle_to_google_sheet/mesa.json
- shopify/customer/add_to_google_sheets_document/mesa.json
- shopify/order/send_to_google_sheets_document/mesa.json
- tiktok/reports/send_daily_adgroup_summary_report/mesa.json
- tracktor/order/send_to_google_sheets/mesa.json
- uploadery/order/add_line_items_to_google_sheet/mesa.json
Readme
mesa.json
Template code
QA
> Google Sheets templates: ensure header rows are added when sheet is created

- pagestudio/page/send_to_another_store/mesa.json
Readme
mesa.json
Template code
QA
> Pagestudio template: Update entity to be page instead of account

- shopify/order/add_payment_gateway_tag/mesa.json
- Asana task: https://app.asana.com/0/393037162945950/1202050233673542
Readme
mesa.json
Template code
QA
> Update Add a payment gateway tag to an order template

- shopify/order/send_to_digital_humani_trees_plant/filter.js
- shopify/order/send_to_digital_humani_trees_plant/mesa.json
Asana task: https://app.asana.com/0/1199933048569373/1202022444316390
Readme
mesa.json
Template code
QA
> Shopify Order Created to Digital Humani tree plant request

- shopify/order/send_to_digital_humani_trees_plant/mesa.json
Readme
mesa.json
Template code
QA
> Digital Humani Template: fix tree count format

- shopify/product/scheduled_product_price_change/mesa.json
- shopify/theme/schedule_change/mesa.json
Readme
mesa.json
Template code
QA
> Rename Scheduler to Schedule in templates

- shopify/order/cancel_high_risk_orders/mesa.json
Readme
mesa.json
Template code
QA
> Enabling Cancel high-risk orders template

- shopify/order/send_to_salesforce_contact/mesa.json
https://app.asana.com/0/393037162945950/1202310172684969
Readme
mesa.json
Template code
QA
> Salesforce: shopify/order/send_to_salesforce_contact: rm jefftest

- shopify/order/send_track_to_segment/mesa.json
Readme
mesa.json
Template code
QA
> Updating Send a Shopify order status update to Segment template description

- collection/shopify_booster_pack/mesa_collection.json
Readme
mesa.json
Template code
QA
> Shopify booster pack

- infiniteoptions/order/send_discord_message/mesa.json
- infiniteoptions/order/track_klaviyo_event/mesa.json
- infiniteoptions/order/yotpo_loyalty_set_birthday/mesa.json
- shopify/order/add_loyaltylion_points/mesa.json
- shopify/order/manually_approve_funds_capture/mesa.json
- shopify/order/send_discord_message_when_tagged/mesa.json
Readme
mesa.json
Template code
QA
> Fix action steps names

- infiniteoptions/order/send_discord_invite_via_email/README.md
- infiniteoptions/order/send_discord_invite_via_email/mesa.json
- shopify/product/send_slack_message_inventory_low/mesa.json
- shopify/refund/google_analytics/mesa.json
Readme
mesa.json
Template code
QA
> Updating "Send a Discord invitation.." template and custom code's descriptions #373

- infiniteoptions/order/send_discord_invite_via_email/mesa.json
Readme
mesa.json
Template code
QA
> Update "Send a Discord invitation when a product using Infinite Options is purchased" email's token

- recharge/customer/update_address_when_customer_updated/mesa.json
Adding a filter to check for email address
Readme
mesa.json
Template code
QA
> Recharge: Update Send an updated address to Recharge when a Shopify customer is updated template

- shopify/order/send_order_paid_message_to_slack/mesa.json
Readme
mesa.json
Template code
QA
> Slack / Pass trigger version in slack template

- bold/subscription/send_notification_on_subscription_product_change/mesa.json
- form/contact_form/mesa.json
- form/shopify_order_return/mesa.json
- infiniteoptions/order/send_slack_notification/mesa.json
- returnly/return/send_to_slack/mesa.json
- shopify/order/send_high_risk_orders_to_slack/mesa.json
- shopify/order/send_international_orders_to_slack/mesa.json
- shopify/product/send_slack_message_inventory_low/mesa.json
Readme
mesa.json
Template code
QA
> Slack / Add versions to slack triggers in templates

- shopify/customer/create_discount_code_for_new_customers/mesa.json
- shopify/order/add_task_to_asana/mesa.json
Readme
mesa.json
Template code
QA
First template: Add a task in Asana when a Shopify order is created
Second template: Create a unique discount code for new customers
> Add 2 new Shopify templates

- shopify/customer/create_discount_code_for_new_customers/mesa.json
Readme
mesa.json
Template code
QA
> Create a unique discount code for new customers template: Remove filter step and reduce to 20% discount

- bold/subscription/send_notification_on_subscription_product_change/mesa.json
- form/contact_form/mesa.json
- form/shopify_order_return/mesa.json
- infiniteoptions/order/send_discord_message/mesa.json
- returnly/return/send_to_slack/mesa.json
- shopify/order/send_high_risk_orders_to_slack/mesa.json
- shopify/order/send_international_orders_to_slack/mesa.json
- shopify/order/send_order_paid_message_to_slack/mesa.json
- shopify/product/send_slack_message_inventory_low/mesa.json
- tests/shopify_order_created_to_email/mesa.json
- tests/template_collection_test/shopify_order_created_to_email/mesa.json
To be pushed with https://github.com/shoppad/ShopPad/pull/8389
Readme
mesa.json
Template code
QA
> Update Slack templates to use v2 of connector

- bold/subscription/send_notification_on_subscription_product_change/mesa.json
- form/contact_form/mesa.json
- form/shopify_order_return/mesa.json
- infiniteoptions/order/send_slack_notification/mesa.json
- returnly/return/send_to_slack/mesa.json
- shopify/order/send_high_risk_orders_to_slack/mesa.json
- shopify/order/send_international_orders_to_slack/mesa.json
- shopify/order/send_order_paid_message_to_slack/mesa.json
- shopify/product/send_slack_message_inventory_low/mesa.json
Readme
mesa.json
Template code
QA
> Slack: Remove lingering v1 tags

- pull_request_template.md
Readme
mesa.json
Template code
QA
> Update pull_request_template.md file

- recharge/order/add_free_product_to_fifth_subscription_order/mesa.json
- recharge/order/add_free_product_to_first_subscription_order/mesa.json
- recharge/order/add_free_product_to_upcoming_order/mesa.json
Updating these templates:
- Add a free product to your customer's Recharge order: https://app.asana.com/0/1199933048569373/1202900999424273
HelpScout Doc: https://secure.helpscout.net/docs/5cba3fdc2c7d3a026fd3d8ec/article/6272c9b7a65f844e77f891a3/
- Add a free product to a customer's first Recharge order: https://app.asana.com/0/1199933048569373/1202716891243079
HelpScout Doc: https://secure.helpscout.net/docs/5cba3fdc2c7d3a026fd3d8ec/article/637583ceb00eaf68a3f3dfb5/
- Add a free product to a customer's fifth Recharge subscription order: https://app.asana.com/0/1199933048569373/1202808421183866
HelpScout Doc: https://secure.helpscout.net/docs/5cba3fdc2c7d3a026fd3d8ec/article/637583dbe1486a4bddba7711/
mesa.json
QA
**Checking each template: Add a free …
> Recharge Templates: Updates

- shopify/customer/create_discount_code_for_new_customers_order/mesa.json
> Add template: Create a unique discount code for new customers to apply towards their next order

- recharge/customer/update_address_when_customer_created/mesa.json
- recharge/customer/update_address_when_customer_updated/mesa.json
Asana Task: [Add missing fields for Recharge steps: List Customers and List Address](https://app.asana.com/0/393037162945950/1203367399344412)
mesa.json
QA
> Recharge: Update names of steps in templates

- shopify/theme/schedule_change/mesa.json
- Related Asana task: https://app.asana.com/0/393037162945950/1203488280656093
- Updated the date in scheduler
mesa.json
QA
> Updating Schedule a Shopify theme change on a specific date and time template

- shopify/product/add_color_tag/mesa.json
> Shopify: Add Filter rule in Add a color tag to a product template

- recharge/order/send_renewal_to_google_analytics/mesa.json
- shopify/refund/google_analytics/mesa.json
> Google Analytics UA: Add version to Google Analytics steps

- shopify/order/send_gift_card_for_orders_over_100/mesa.json
> Add template: Send a $20 gift card to a customer if they spend $100 or more

- gorgias/ticket/send_gift_card_when_order_delayed/mesa.json
> Add template: Send a gift card to a customer if their order is delayed

- gorgias/ticket/send_gift_card_when_order_delayed/mesa.json
Update text **order-delayed** to **send-gift-card** in Filter step.
mesa.json
QA
> Update template: Send a gift card to a customer if their order is delayed

- shopify/customer/create_discount_code_for_new_customers/mesa.json
Template: Create a unique discount code for new customers to apply towards a specific product
mesa.json
QA
> Shopify: Change name & slug in discount template

- shopify/customer/generate_product_discount_code_for_new_customers/mesa.json
Template: Create a unique discount code for new customers to apply towards a specific product
mesa.json
QA
> Shopify: Change folder name to match template slug

- shopify/theme/schedule_change/mesa.json
Making merchants select the date
mesa.json
QA
> Update date selection for Schedule a Shopify theme... template

- recharge/order/send_renewal_to_google_analytics/mesa.json
- GA Create Transaction step needed version: https://app.asana.com/0/393037162945950/1203793988825641
mesa.json
QA
> Update step version (UA) in Send Recharge renewal data to Google Analytics template

- yotpo/review/send_a_thank_you_email/mesa.json
> Yotpo: Add Send a thank you email when a review is created in Yotpo template

- infiniteoptions/order/send_slack_notification/README.md
- infiniteoptions/order/send_slack_notification/mesa.json
- Asana Task: https://app.asana.com/0/393037162945950/1203872241651366
- Brings up the bigger question on whether we should update the Admin URLs in all templates - probably won't work 100% of the time immediately since it depends on whether Shopify has updated your store to use the new admin url
mesa.json
QA
> Infinite Options: Update Send a Slack notification... template

- shopify/order/send_high_risk_orders_to_slack/mesa.json
- Template: Receive a Slack message when Shopify flags an order as high-risk
- Asana Task: https://app.asana.com/0/393037162945950/1203872241651388
mesa.json
QA
> Shopify: Update Receive a Slack message when Shopify flags... template

- delighted/survey/send_slack_message_if_low_delighted_survey_score/mesa.json
> Delighted: Add Send a Slack message when a customer gives a low Delighted survey score template

- shopify/product/create_product_descriptions_with_aibymesa/mesa.json
> Shopify: Add Write Shopify product descriptions with AI by MESA template

- bin/README.md
- bin/index.js
- bin/migrations/01-update-trigger-names.js
- bin/migrations/02-fine-tune-gpt-3.js
- bin/namedConcat.js
- package.json
> Updating bin scripts for GPT training

- shopify/order/add_fulfillment/mesa.json
- shopify/order/create_shipstation_label/mesa.json
- shopify/order/send_digital_download/mesa.json
PR: https://github.com/shoppad/ShopPad/pull/8755
mesa.json
QA
> Support Shopify Fulfillment updates

- shopify/order/send_gift_card_for_orders_over_100/mesa.json
- shopify/order/send_to_delighted_nps_survey/mesa.json
**Asana Tasks:**
- https://app.asana.com/0/770345770753602/1204205028596117
- https://app.asana.com/0/770345770753602/1204188103131600
**Templates:**
- Send a $20 gift card to a customer if they spend $100 or more
- Send a Delighted NPS survey to a customer after they place an order
**Updating wrong variables to use the Delay variables:**
mesa.json
QA
> Update 2 templates to use the Delay variables

- shopify/product/add_to_etsy_listing/mesa.json
Add Shopify Retrieve Product action after Shopify Product Created trigger to retrieve the product's images. Shopify Product Created does not include the images anymore.
Add in the Etsy Upload Image on Listing action to include an image to the Etsy draft listing.
[Asana Ticket](https://app.asana.com/0/393037162945950/1204171561462383/f)
mesa.json
QA
> Update Add a listing on Etsy when a new product is created in Shopify template

- shopify/product/write_product_descriptions_with_openai/mesa.json
Related to this [Asana ticket](https://app.asana.com/0/393037162945950/1204284549167747/f).
mesa.json
> Update openAI model in Use OpenAI to write your product descriptions template

- shopify/product/send_slack_message_inventory_low/custom.js
- shopify/product/send_slack_message_inventory_low/mesa.json
Asana Task: [Update: Send a Slack message when inventory runs low](https://app.asana.com/0/1199933048569373/1204171561462350)
mesa.json
> Update template: Send a Slack message when inventory runs low

- shopify/order/add_task_to_asana/mesa.json
Asana Task: [Update: Add a task in Asana when a Shopify order is created](https://app.asana.com/0/1199933048569373/1204373036195636/f)
mesa.json
> Update template: Add a task in Asana when a Shopify order is created

- shopify/customer/create_discount_code_for_new_customers_order/mesa.json
Add Filter step to check for phone number.
Replaced Email by MESA with SMS by MESA.
Asana: [Update: 'Create a unique discount code for new customers to apply towards their next order' template to use SMS instead](https://app.asana.com/0/393037162945950/1204171561462330/f)
mesa.json
> Update template: Create a unique discount code for new customers to apply towards their next order

- shopify/customer/generate_product_discount_code_for_new_customers/mesa.json
Updated incorrect folder via [Update template: Create a unique discount code for new customers to apply towards a specific product #435](https://github.com/shoppad/mesa-templates/pull/435).
mesa.json
> Update template: Create a unique discount code for new customers to apply towards a specific product

- infiniteoptions/order/send_email/mesa.json
- pack/shopify_booster_pack/mesa_collection.json
- shopify/customer/tag_customers_with_edu_email/mesa.json
- shopify/customer/tag_vip_customers/mesa.json
- shopify/draft_order/remove_after_thirty_days/mesa.json
- shopify/order/add_customers_orders_to_notes/mesa.json
- shopify/order/add_payment_gateway_tag/mesa.json
- shopify/order/add_product_tag/mesa.json
- shopify/order/cancel_high_risk_orders/mesa.json
- shopify/order/receive_sms_when_order_created/mesa.json
- shopify/order/send_email_notification_when_order_has_notes/mesa.json
- shopify/order/send_expedited_shipping_alert_to_logistics/mesa.json
- shopify/order/send_high_risk_orders_to_sms/mesa.json
- shopify/order/send_order_report_card_email/mesa.json
- shopify/product/add_color_tag/mesa.json
- shopify/product/automatically_publish/mesa.json
- shopify/product/create_product_descriptions_with_aibymesa/mesa.json
- shopify/product/send_email_when_product_goes_out_of_stock/mesa.json
- shopify/product/update_when_out_of_stock/mesa.json
- tracktor/fulfillment/add_tag_with_current_delivery_status/mesa.json
- tracktor/fulfillment/delay_in_transit_email/mesa.json
- tracktor/fulfillment/delay_in_transit_sms/mesa.json
- tracktor/fulfillment/send_email_when_in_transit/mesa.json
- tracktor/fulfillment/send_sms_when_order_delivered/mesa.json
> Booster pack update

- shopify/customer/tag_vip_customers/mesa.json
> Add wizard steps to tag vip customer

- shopify/customer/add_new_customer_to_quickbooks/mesa.json
- Asana Task: https://app.asana.com/0/1199933048569373/1203582983765973
- QA'd by Jen
mesa.json
> Add Add a customer in Quickbooks when a new customer is created in Shopify template

- shopify/product/add_and_remove_tags_on_new_products/mesa.json
Update description for question. 
Asana Task: [Add a tag to a new product and then remove the tag after 30 days](https://app.asana.com/0/0/1203704956362090/1204480811576217/f)
mesa.json
> Update template: Add a tag to a new product and then remove the tag after 30 days

- form/start_return_with_gorgias_ticket/mesa.json
- gorgias/ticket/send_gift_card_when_order_delayed/mesa.json
- yotpo/review/create_gorgias_ticket/mesa.json
> Add version to Gorgias steps in existing templates

- unsearchable/shopify/order/create_test_orders/mesa.json
> New template to create test orders

- shopify/order/lock_editing_with_tags/mesa.json
> Add template setup: Tag an order after a Shopify order is created and update the same tag 24 hours later

- shopify/draft_order/send_email_notification/mesa.json
> Mesa / Add setup steps to draft order email template

- shopify/order/send_expedited_shipping_alert_to_logistics/mesa.json
> Add template setup: Tag an order when expedited shipping is selected

- shopify/product/send_email_when_product_goes_out_of_stock/mesa.json
> Add template setup to 'Receive an email when a product goes out of stock'

- recharge/order/add_free_product_to_first_subscription_order/mesa.json
Add template setup.
Asana Task: [Template setup: Add a free product to a customer's first Recharge order](https://app.asana.com/0/1199933048569373/1204615893171771/f)
mesa.json
> Update template: Add a free product to a customer's first Recharge order

- shopify/product/use_chatgpt_to_write_product_descriptions/mesa.json
Asana Task: [Write product descriptions with ChatGPT](https://app.asana.com/0/1199933048569373/1204498042157921/f)
mesa.json
> Add template: Write product descriptions with ChatGPT

- shopify/order/update_tracktor_status_when_order_tag_added/README.md
- shopify/order/update_tracktor_status_when_order_tag_added/mesa.json
Asana Task: [Core apps: Convert templates to use template setup](https://app.asana.com/0/1199933048569373/1204509990728457/f)
mesa.json
> Add template setup: Update Tracktor status when an order tag is added in Shopify

- infiniteoptions/order/date_field_add_tag/mesa.json
- tracktor/order/automatic_custom_status/mesa.json
- uploadery/order/send_file_to_google_drive/README.md
- uploadery/order/send_file_to_google_drive/mesa.json
Add template setup to these templates.
- Send Uploadery Files to Google Drive
- Add a tag to orders containing product options with a date field
- Update tracking to a custom status
mesa.json
> Add template setup round 1

- form/yotpo_loyalty_customer_dob/mesa.json
- Asana Task: https://app.asana.com/0/393037162945950/1204607422326458/f
mesa.json
> Update Save a customer's birthday to a Yotpo Loyalty customer template

- etsy/order/send_to_google_sheets/mesa.json
Asana Task: [Send Etsy orders to Google Sheets](https://app.asana.com/0/1199933048569373/1203281752694246/f)
mesa.json
> Add template: Send Etsy orders to Google Sheets

- shopify/product/send_to_salesforce_product_and_pricebook_entry/mesa.json
Required by this change https://app.asana.com/0/1200281847911314/1204909026194513/f
mesa.json
> Salesforce template: downgrade loop schema to 4

- shopify/checkout/send_abandoned_carts_to_google_sheets/mesa.json
Asana Task: [Get list of abandoned carts every X minutes/hour and send details to Google Sheet](https://app.asana.com/0/1199933048569373/1204240228289250/f)
mesa.json
> Add template: Send a list of abandoned carts to Google Sheets

- shopify/checkout/send_abandoned_carts_to_google_sheets/mesa.json
Change Schedule trigger to run on an hourly basis.
mesa.json
> Update template: Send a list of abandoned carts to Google Sheets

- tracktor/fulfillment/email_when_package_takes_too_long/mesa.json
Check "Skip delay when running a test or when this step is replayed".
Apps Weekly Asana Task: [Delay not automatically skipped during testing ](https://app.asana.com/0/393037162945950/1204990466403185/f)
mesa.json
> Update template: Send an email if a package hasn't been delivered

- shopify/product/tag_product_with_metafield_when_product_updated/mesa.json
Asana Task: [Tag a product with a metafield value](https://app.asana.com/0/1199933048569373/1204498444352934/f)
mesa.json
> Add template: Tag a product with a metafield value

- shopify/customer/tag_vip_customers/mesa.json
- Fix the Filter step so it is "greater than or equal to".
- [Apps Weekly Asana Task](https://app.asana.com/0/393037162945950/1205065486075585/f)
mesa.json
> Fix template: Tag customers with VIP after they spend  or more

- fera/review/tag_customers_who_leave_more_than_two_reviews/mesa.json
[MESA Templates Asana Task](https://app.asana.com/0/1199933048569373/1204883934473594/f)
mesa.json
> Add template: Tag customers when they leave more than 2 reviews

- shopify/order/tag_customer_when_specific_product_purchased/mesa.json
- Template Setup language updates
- [MESA Templates Asana Task](https://app.asana.com/0/0/1204498444352936/1205105380069521/f)
mesa.json
> Update template: Tag a customer when they purchase a specific product

- shopify/product/add_to_etsy_listing/mesa.json
[MESA Templates Asana Task](https://app.asana.com/0/1199933048569373/1205115602490036/f)
mesa.json
> Add template setup: Add a listing on Etsy when a new product is created in Shopify

- shopify/product/add_to_etsy_listing/mesa.json
[MESA Templates Asana Task](https://app.asana.com/0/1199933048569373/1205115602490036/f)
mesa.json
> Update template: Add a listing on Etsy when a new product is created in Shopify

- shopify/customer/tag_customers_with_edu_email/mesa.json
- Add template setup
- Update "Educational Discount" to "Educational" tag
mesa.json
> Update template: Add an educational discount tag to a customer

- shopify/customer/tag_customers_with_edu_email/mesa.json
Related to https://github.com/shoppad/mesa-templates/pull/486.
mesa.json
> Update tag: Add an educational discount tag to a customer

- shopify/order/send_file_to_dropbox/mesa.json
- [MESA Templates Asana Task](https://app.asana.com/0/1199933048569373/1205167970689641/f)
mesa.json
> Update template: Send files from a Shopify order to Dropbox

- ftp/update_shopify_inventory_with_csv_file/custom.js
- ftp/update_shopify_inventory_with_csv_file/loop.js
- ftp/update_shopify_inventory_with_csv_file/mesa.json
- [MESA Templates Asana Task](https://app.asana.com/0/1199933048569373/1205318761444956/f)
mesa.json
> Add template: Update Shopify inventory levels from a CSV file on an FTP server

- ftp/update_shopify_inventory_with_csv_file/mesa.json
- Language updates from [MESA Templates Asana Task](https://app.asana.com/0/0/1205318761444956/1205349111181557/f)
mesa.json
> Update template: Update Shopify inventory levels from a CSV file on an FTP server

- shopify/customer/add_to_google_sheets_document/mesa.json
- [MESA Templates Asana Task](https://app.asana.com/0/1199933048569373/1205236547340540/f)
mesa.json
> Add template setup: Add a Shopify customer to Google Sheets

- infiniteoptions/order/send_discord_invite_via_email/mesa.json
- [Engineering Inbox Asana Task](https://app.asana.com/0/1200281847911314/1205443820968872/f)
mesa.json
> Update template: Email a Discord invitation when a product using Infinite Options is purchased

- shopify/order/add_fulfillment/mesa.json
- [MESA Templates Asana Task](https://app.asana.com/0/0/1205452796090548/1205511632264789/f)
mesa.json
> Update template: Add fulfillment to line items that don't require shipping

- shopify/product/generate_shopify_product_tags_with_ai_by_mesa/mesa.json
- [MESA Templates Asana Task](https://app.asana.com/0/1199933048569373/1205236544837232/f)
mesa.json
> Add template: Use AI by MESA to generate Shopify product tags

- shopify/product/create_discord_channel_message/mesa.json
- [MESA Templates Asana Task](https://app.asana.com/0/1199933048569373/1205062372153414/f)
mesa.json
> Add template: Create a channel message when a new product is created in Shopify

- shopify/customer/create_discount_code_for_new_customers_order/mesa.json
- MESA Templates Asana Task: [Wizard: Create a unique discount code for new customers to apply towards their next order](https://app.asana.com/0/1199933048569373/1205349111181565/f)
mesa.json
> Add template setup: Create a unique discount code for new customers to apply towards their next order

- infiniteoptions/order/track_klaviyo_event/mesa.json
- shopify/customer/add_email_to_klaviyo_list/mesa.json
- shopify/customer/backorder_tag_to_klaviyo_email_list/mesa.json
- shopify/order/subscribe_shoppers_to_klaviyo_list/mesa.json
- unsearchable/tracktor/fulfillment/sync-to-klaviyo/mesa.json
- Related: https://github.com/shoppad/ShopPad/pull/9394
mesa.json
> Add version to Klaviyo steps for existing templates

- shopify/product/generate_shopify_product_tags_with_ai_by_mesa/mesa.json
> Updating prompt for the new model

- judgeme/review/mesa.json
Asana: [Add a tag to a Shopify customer if they leave a review](https://app.asana.com/0/1199933048569373/1206052395730289/f)
mesa.json
> Add template: Add a tag to a Shopify customer if they leave a review

- fera/media/post_to_pinterest_when_media_is_approved/mesa.json
- shopify/product/create_a_pin/mesa.json
Asana
- [Post to Pinterest when media is approved](https://app.asana.com/0/1199933048569373/1205040957423869/f)
- [Create a pin when a Shopify product is created](https://app.asana.com/0/1199933048569373/1206052395730297/f)
2 templates to QA
**Post to Pinterest when media is approved**
**Create a pin when a Shopify product is created**
mesa.json
> Pinterest: Add templates

- loopreturns/return/send_to_slack/mesa.json
Asana: [Send a Slack message when a return in Loop Returns has been authorized](https://app.asana.com/0/1199933048569373/1205458398219273/f)
- `Authorized return. Return ID: 46331764`
mesa.json
> Add template: Send a Slack message when a return in Loop Returns has been authorized

- square/customer/add_to_klaviyo_subscribe_list/mesa.json
Asana: [Add new Square customers to a Klaviyo subscribe list](https://app.asana.com/0/1199933048569373/1205934765762562/f)
mesa.json
> Add template: Add new Square customers to a Klaviyo subscribe list

- square/customer/add_to_klaviyo_subscribe_list/mesa.json
- Asana: https://app.asana.com/0/0/1205934765762562/1206436189270995/f
mesa.json
> Update template: Add new Square customers to a Klaviyo subscribe list

- shopify/order/send_order_customer_details_to_odoo/mesa.json
- Reducing the number of escalations by removing these filled in values that cause errors: https://supportr.helpscoutdocs.com/article/1838-internal-mesa-troubleshooting-odoo-customer-create-error
- Fields are probably from GLDN
mesa.json
> Odoo: Template - Remove problematic fields

- shopify/order/send_order_customer_details_to_odoo/mesa.json
- shopify/order/send_order_customer_details_to_odoo/transform_mapping_2.js
- Jen/Jeff agreed to not support sending taxes, shipping, discounts information in this template. These dummy products complicate the setup process and cause a lot of issues.
User:
mesa.json
> Odoo: Send Shopify order and customer details to Odoo template - Remove Taxes, Shipping, Discounts

- shopify/refund/google_analytics/custom.js
- shopify/refund/google_analytics/mesa.json
- Asana Task: https://app.asana.com/0/1199933048569373/1202496217522427/f
**Complete the rest of the QA steps when completely free. Otherwise, you will need to trigger the template multiple times if you don't have time to check the Realtime Report**
mesa.json
> Update Track Shopify refunds in Google Analytics template

- shopify/customer/generate_product_discount_code_for_new_customers/mesa.json
- Asana: [Wizard: Create a unique discount code for new customers to apply towards a specific product](https://app.asana.com/0/1199933048569373/1205349111181569/f)
mesa.json
> Add template setup: Create a unique discount code for new customers to apply towards a specific product

- form/wholesale_application/mesa.json
- Asana: [Wizard: Send wholesale applications to Google Sheets](https://app.asana.com/0/1199933048569373/1205452793972394/f)
mesa.json
> Add template setup: Send wholesale applications to Google Sheets

- shopify/product/scheduled_product_price_change/mesa.json
- Asana: [Wizard: Update 'Schedule a product price change'](https://app.asana.com/0/1199933048569373/1205188123696620/f)
mesa.json
> Add template setup: Schedule a product price change

- shopify/product/scheduled_product_price_change/mesa.json
- Copy updates
- Asana: [Wizard: Update 'Schedule a product price change'](https://app.asana.com/0/0/1205188123696620/1206985399980706/f)
mesa.json
> Update template: Schedule a product price change

- infiniteoptions/order/send_discord_invite_via_email/mesa.json
- infiniteoptions/order/send_discord_message/mesa.json
- shopify/product/create_discord_channel_message/mesa.json
Asana
- [Update: 'Send a Discord message when a product using Infinite Options is purchased' template](https://app.asana.com/0/562906963533984/1207395531043352/f)
- [Update: 'Create a channel message when a new product is created in Shopify' template](https://app.asana.com/0/562906963533984/1207395531043361/f)
- [Update: 'Email a Discord invitation when a product using Infinite Options is purchased' template](https://app.asana.com/0/562906963533984/1207395531043370/f)
mesa.json
> Update Discord instructions on template setup

- tracktor/fulfillment/send_gmail_email_when_package_is_in_transit/mesa.json
Asana: [Send an email via Gmail when a package is "In Transit" ](https://app.asana.com/0/562906963533984/1207815975164587/f)
mesa.json
> Add template: Send an email via Gmail when a package is 'In Transit'

- shopify/order/tag_order_when_specific_discount_code_is_used/mesa.json
Asana: [Tag an order when a specific discount code is applied](https://app.asana.com/0/562906963533984/1204342340814575/f)
mesa.json
> Add template: Tag an order when a specific discount code is applied

- shopify/customer/add_to_google_sheets_document/mesa.json
> Update 'Add a Shopify customer to Google Sheets' to use Google Sheets v2

- google_sheets/row/send_gmail_email_from_googlesheets/mesa.json
- Copy changes
- Asana: [Send an email from a new row in Google Sheets](https://app.asana.com/0/0/1207815975164582/1207927917742727/f)
mesa.json
> Update 'Send an email from a new row in Google Sheets' template

- google_sheets/row/send_gmail_email_from_googlesheets/mesa.json
> Update title of 'Send an email from Gmail when a Google Sheet row is added' template

- uploadery/order/send_email/mesa.json
Updated Email Step to v2
mesa.json
> Update 'Send an email when an Uploadery order is created' template

- shopify/order/cancel_high_risk_orders/mesa.json
> Fix Automatically Cancel High-Risk Orders and Notify Customer template

- ftp/update_shopify_inventory_with_csv_file/mesa.json
- ftp/update_shopify_product_prices_with_csv/mesa.json
- shopify/order/send_to_spa_ftp_file/mesa.json
- spa/fulfillment/send_to_shopify/mesa.json
- tests/kitchen_sink/mesa.json
- unsearchable/ftp/inventory_update_shopify/mesa.json
> FTP V2 Update

- ftp/update_shopify_inventory_with_csv_file/mesa.json
- ftp/update_shopify_product_prices_with_csv/mesa.json
- shopify/order/send_to_spa_ftp_file/mesa.json
- spa/fulfillment/send_to_shopify/mesa.json
- tests/kitchen_sink/mesa.json
- unsearchable/ftp/inventory_update_shopify/mesa.json
Reverts shoppad/mesa-templates#638
> Revert "FTP V2 Update"

- ftp/update_shopify_inventory_with_csv_file/mesa.json
- Missed one from: https://github.com/shoppad/mesa-templates/pull/645
mesa.json
> Add v1 to FTP template

- mcp/email/send_email/mesa.json
- mcp/shopify/retrieve_customers/mesa.json
- mcp/shopify/retrieve_orders/mesa.json
> MCP restructure into mcp dir

- ask/analyize_help_scout_conversations/ask_help_scout_conversations/mesa.json
- ask/analyize_help_scout_conversations/mesa_collection.json
> Add ask/analyize_help_scout_conversations template collection

- shopify/gift_card/sync_balance_to_klaviyo_profile_kj/mesa.json
- Updating template to Klaviyo v4
mesa.json
> Update Sync Shopify Gift Card Balances to Klaviyo Profiles template

- ask/analyze_help_scout_conversations/ask_help_scout_conversations/mesa.json
- mcp/helpscout/retrieve_conversations/mesa.json
- mcp/shopifypartners/retrieve_usage_charges/mesa.json
> MCP Template language updates

- yotpoloyalty/customer_points/send_to_omnisend_contact/mesa.json
…
https://app.asana.com/1/71291173468390/project/393037162945950/task/1210792695607088?focus=true
mesa.json
> Sync Yotpo Points Balance to Omnisend Contacts: Template: Remove ampersand from step title
