- mesa/file/send-to-google-cloudprint/README.md
Readme
mesa.json
Template code
QA
> fix oath url for cloudprint automation

- shopify/order/add_created_tag_updated_tag/mesa.json
Readme
mesa.json
Template code
QA
> Mesa: add Order tag / update automation

- infiniteoptions/order/add-line-item-tag-to-order-after-order-creation/mesa.json
- infiniteoptions/order/date_field_add_tag/mesa.json
Before testing:
Readme
mesa.json
Template code
QA
> Adding add_line_item_tag_to_order_after_order_creation template

- tracktor/order/send_to_stampedio_review_request/mesa.json
Instructions:
Readme
mesa.json
Template code
QA
> Adding send_to_stampedio_review_request tracktor order template

- shopify/refund/google_analytics/custom.js
- shopify/refund/google_analytics/mesa.json
Readme
mesa.json
Template code
QA
> Add google_analytics template

- tracktor/order/automatic_custom_status/mesa.json
Instructions
Readme
mesa.json
Template code
QA
> Adding automatic_custom_status template

- tracktor/order/send_to_google_sheets/custom.js
- tracktor/order/send_to_google_sheets/mesa.json
Readme
QA Steps:
Available tracking numbers if needed:
- 420060959300120207600324868438 USPS
- 1ZV254916813504832 UPS
- 520697757 TNT
- YT2110021272219856 Yun Express
mesa.json
Template code
QA
> Adding tracktor/order/send_to_google_sheets template

- infiniteoptions/order/send_discord_invite_via_email/README.md
- infiniteoptions/order/send_discord_invite_via_email/mesa.json
- Send a Discord invitation to a customer when they purchase a tagged product using Infinite Options
QA 
Readme
mesa.json
Template code
QA
> Send a Discord invitation to a customer when they purchase a tagged product using Infinite Options

- webhook/send_to_flow/mesa.json
Language + install steps: https://app.asana.com/0/1199933048569373/1200387078445665
Readme
mesa.json
Template code
QA
> Trigger a Shopify Flow workflow from any service

- tracktor/order/refund_shipping_cost/mesa.json
Readme
mesa.json
Template code
QA
> Adding tracktor/order/refund_shipping_cost template

- shopify/order/daily_export_to_google_sheets/mesa.json
Readme
mesa.json
Template code
QA
> Adding daily_export_to_google_sheets

- infiniteoptions/order/send_slack_notification/README.md
- infiniteoptions/order/send_slack_notification/mesa.json
- Send Slack Notification When Infinite Options Tagged Product is Purchase
QA:
Readme
mesa.json
Template code
QA
> Adding infiniteoptions/order/send_slack_notification template

- infiniteoptions/order/send_email/README.md
- infiniteoptions/order/send_email/mesa.json
QA:
Readme
mesa.json
Template code
> Adding infiniteoptions/order/send_email template

- tracktor/order/send_sms_when_order_delivered/mesa.json
- tracktor/order/send_twilio_sms_when_order_delivered/mesa.json
* Update tracktor/order/send_sms_when_order_delivered to use built-in sms <- swap out existing prismic entry to reflect that is uses built-in sms
*Add twilio-specific template: tracktor/order/send_twilio_sms_when_order_delivered/ <- this will be a new entry in prismic
Readme
mesa.json
Template code
QA
> tracktor/order/send_sms_when_order_delivered with built-in sms

- tracktor/fulfillment/delay_in_transit_sms/README.md
- tracktor/fulfillment/delay_in_transit_sms/mesa.json
- tracktor/fulfillment/delay_in_transit_twilio_sms/README.md
- tracktor/fulfillment/delay_in_transit_twilio_sms/mesa.json
Add tracktor/fulfillment/delay_in_transit_sms <- swap out existing prismic entry to reflect that is uses built-in sms
Rename twilio sms template tracktor/fulfillment/delay_in_transit_twilio_sms/ <- this will be a new entry in prismic
Readme
mesa.json
Template code
QA
> Add tracktor/fulfillment/delay_in_transit_sms using built-in SMS

- form/send_quote/mesa.json
QA Instructions
Readme
mesa.json
Template code
QA
> Add form/send_quote template

- infiniteoptions/order/yotpo_loyalty_set_birthday/custom.js
- infiniteoptions/order/yotpo_loyalty_set_birthday/mesa.json
Related Ticket: (Read me and content) -> https://app.asana.com/0/1199933048569373/1200679847073186
QA
Readme
mesa.json
Template code
> Adding infiniteoptions/order/yotpo_loyalty_set_birthday template

- shopify/order/manually_approve_funds_capture/custom.js
- shopify/order/manually_approve_funds_capture/mesa.json
We are hardcoding a value in one of the steps for testing purpose it. 
Related Ticket -> https://app.asana.com/0/1199933048569373/1200468712958426
) 
) 
Readme
mesa.json
Template code
> Adding shopify/order/manually_approve_funds_capture template

- infiniteoptions/order/track_klaviyo_event/mesa.json
Related ticket -> https://app.asana.com/0/1199933048569373/1200672646708095
Content still been worked on.
QA
Readme
mesa.json
Template code
> Adding infiniteoptions/order/track_klaviyo_event template

- shopify/order/approve_thank_you_email/mesa.json
Related ticket -> https://app.asana.com/0/1199933048569373/1200468712958426
Readme
mesa.json
Template code
QA
> Adding shopify/order/approve_thank_you_email template

- form/shopify_order_return/mesa.json
Readme
mesa.json
Template code
QA
> Start a Return with Mesa Forms - add order_id default value

- shopify/order/add_line_item_properties_to_notes/mesa.json
Readme
mesa.json
Template code
QA
> Fixing the order_note token in Add Line Item Properties to Order Notes template

- shopify/order/create_google_sheet/mesa.json
Readme
mesa.json
Template code
QA
> Add shopify/order/create_google_sheet template

- shopify/customer/tag_customer_vip/mesa.json
Readme
mesa.json
Template code
QA
> Add shopify/customer/tag_customer_vip template

- shopify/customer/tag_customers_with_edu_email/mesa.json
This template appears to be broken (it is trying to update the order tag instead of the customer tag) This PR changes the output from the "Shopify Order Update" to "Shopify Add Customer Tag".
Readme
mesa.json
Template code
QA
> Fix / tag customers with edu email

- shopify/order/add_line_item_properties_to_notes/mesa.json
Readme
mesa.json
Template code
QA
> Enable "Add Line Item Properties to Order Notes" by default

- shopify/product/send_digital_download/mesa.json
Readme
mesa.json
Template code
QA
> send_digital_download

- tracktor/order/send_postcard_when_order_delivered/mesa.json
Readme
mesa.json
Template code
QA
- Design tab in our account
- Choose a design and click view details
- Design ID and Mail Class can be found in the JSON Examples when you scroll down
- Key = Field in the Design Variables of the Design you've selected and Value = Field Type in the Design Variables
> send_postcard_when_order_delivered

- shopify/order/send_discord_message_when_tagged/mesa.json
Readme
mesa.json
Template code
QA
> send_discord_message_when_tagged

- infiniteoptions/order/add_product_bundle_to_google_sheet/custom.js
- infiniteoptions/order/add_product_bundle_to_google_sheet/mesa.json
New template to send IO product bundles to Google Sheets. Details: https://app.asana.com/0/1201100554677827/1201100617205817
Readme - notes are currently here, awaiting Marketing / prismic entry: https://app.asana.com/0/1201100554677827/1201100617205817 
mesa.json
Template code
QA
> Infinite Options: Send Product Bundles to Google Sheets

- shopify/order/send_email_notification_when_order_has_notes/mesa.json
Readme
mesa.json
Template code
QA
> Enable 'Send Email Notification To Store Owner When Shopify Order Has Notes' by default

- infiniteoptions/order/send_email/README.md
- shopify/order/cancel_and_restock_high_risk_orders/mesa.json
Readme
mesa.json
Template code
QA
> Mesa: Update risky order template, minor IO email readme update

- shopify/order/add_line_item_properties_to_notes/mesa.json
Readme
mesa.json
Template code
QA
> Shopify Order Line Item Properties to Notes: preserve existing notes

- infiniteoptions/order/send_email/mesa.json
- By default now has no IO field selected
- Template is enabled by default
Draft updated docs:
Prismic draft: https://mesa.prismic.io/documents~b=working&c=unclassified&l=en-us/YPC99xAAACIAjmbl/?section=Main
Helpscout draft: https://secure.helpscout.net/docs/5cba3fdc2c7d3a026fd3d8ec/article/617c7b462b380503dfdffe58/
Readme
mesa.json
Template code
QA
> IO Product Purchased to Email - simplify

- shopify/order/send_high_risk_orders_to_slack/mesa.json
- shopify/order/send_high_risk_orders_to_sms/mesa.json
Fix template typos per: https://app.asana.com/0/393037162945950/1201419431999930
Readme
mesa.json
Template code
QA
> Mesa: fix input action for high risk order templates

- shopify/order/send_thanks_io_postcard/mesa.json
Readme
mesa.json
Template code
QA
> Thanks.io: disable autoenable on template

- shopify/order/send_to_google_sheets_document/mesa.json
Fix capitalization of Loop step's title to "Loop over each product in the order" on the Send orders to Google Sheets template.
Readme
mesa.json
Template code
QA
> Fix capitalization on Loop step

- shopify/order/add_free_product_when_customer_tagged/mesa.json
Readme
mesa.json
Template code
QA
> Recharge: Add a Free Onetime Product to a Recharge Order to use fields

- recharge/order/add_shopify_customer_tag/mesa.json
- recharge/order/when_cancelled_remove_shopify_customer_tag/mesa.json
Test out the following themplates
- Remove a Shopify customer tag when a Recharge subscription product is canceled
- Tag a customer when a subscription is purchased
Readme
mesa.json
Template code
QA
> Recharge: Tagging customer when subscription it's created updates

- recharge/order/add_free_product_to_upcoming_order/mesa.json
Readme
mesa.json
Template code
QA
> Publishing Add a free product to your customer's upcoming order template

- recharge/customer/update_address_when_customer_created/mesa.json
Readme
mesa.json
Template code
QA
> Add template: Update an address in Recharge when a customer is created in Shopify

- recharge/order/add_free_product_to_order_customer_tag/mesa.json
Readme
mesa.json
Template code
QA
> Add template: Add a free product to an upcoming order when a tag is added to the customer

- shopify/order/cancel_and_restock_high_risk_orders/mesa.json
- shopify/order/cancel_high_risk_orders/mesa.json
Readme
mesa.json
Template code
QA
> Updating Cancel high-risk orders template

- tracktor/order/update_status_shipping_method/mesa.json
Readme
mesa.json
Template code
QA
> Updating Update a custom order status in Tracktor and send an email if "Express" shipping is enabled template

- tracktor/fulfillment/automatically_set_custom_status/mesa.json
- tracktor/order/automatically_set_custom_status/mesa.json
Readme
mesa.json
Template code
QA
> Updating Delay custom order status updates template

- recharge/order/tag_order_when_processed_with_recharge/mesa.json
Readme
mesa.json
Template code
QA
> Add Tag an order when processed with Recharge

- shopify/order/send_track_to_segment/mesa.json
- tracktor/fulfillment/send_track_to_segment/mesa.json
Templates:
- Send a Shopify order status update to Segment
- Send a Tracktor fulfillment status update to Segment
Readme
mesa.json
Template code
QA
**Send a Shopify order status update to Segment:**
**Send a Tracktor fulfillment status update to Segment:**
> Update Mesa Segment templates

- pack/shopify_booster_pack/mesa_collection.json
Readme
mesa.json
Template code
QA
> Shopify Booster Pack: Rename to pack folder

- shopify/order/send_file_to_dropbox/mesa.json
Readme
mesa.json
Template code
QA
> Adding Send files from a Shopify order to Dropbox  template

- form/yotpo_loyalty_customer_dob/mesa.json
- shopify/order/edit_add_product/mesa.json
Asana Ticket: [Action titles do not display as inputted in Prismic](https://app.asana.com/0/393037162945950/1202662479069891/f)
Readme
mesa.json
Template code
QA
> Fix names of actions in templates

- recharge/order/add_free_product_to_order_customer_tag/mesa.json
- recharge/order/add_free_product_to_upcoming_order/mesa.json
- shopify/order/send_high_risk_orders_to_sms/mesa.json
Readme
mesa.json
Template code
QA steps for templates: **Add a free product to your customer's upcoming order** & A**dd a free product to an upcoming order when a tag is added to the customer**
1. https://docs.getmesa.com/article/1494-add-free-product-to-your-customers-upcoming-order
2. https://docs.getmesa.com/article/1496-add-free-product-to-upcoming-order-when-tag-is-added-to-the-customer
QA steps for template: **Receive an SMS message when someone creates a fraudulent order**
> Updating Recharge "Add a free product..." templates & Shopify SMS order risk template

- shopify/order/lock_editing_with_tags/mesa.json
Readme
mesa.json
Template code
QA
> Updating "Add "Order Can Be Edited" tag"... template

- shopify/customer/add_email_to_mailchimp_list/mesa.json
Readme
mesa.json
Template code
QA
> Fix name of Mailchimp action in a template

- shopify/product/send_to_salesforce_product_and_pricebook_entry/mesa.json
…duct and Pricebook Entry
Readme
mesa.json
Template code
QA
> Update trigger on template to just Product Updated: Shopify to Salesforce Product and Pricebook Entry

- shopify/product/send_to_salesforce_product_and_pricebook_entry/mesa.json
- Change "Product Updatedd" to "Product Updated"
Readme
mesa.json
Template code
QA
> Fix trigger typo in Send an updated or new Shopify Product to a Salesforce Product and Pricebook entry template

- shopify/order/add_free_product_when_discount_code_applied/mesa.json
- shopify/order/receive_sms_when_order_created/mesa.json
Readme
mesa.json
Template code
QA
> Oct 2022: Adding two new Shopify Order templates

- shopify/order/send_expedited_shipping_alert_to_logistics/filter.js
- shopify/order/send_expedited_shipping_alert_to_logistics/mesa.json
In the Tag an order when expedited shipping is selected template, the custom code in the Filter step is an old version so I replaced by removing the Filter step and re-adding it.
mesa.json
QA
> Update Filter step in Tag an order when expedited shipping is selected template

- shopify/order/add_customers_orders_to_notes/mesa.json
Changes made to this template after the https://github.com/shoppad/ShopPad/pull/8646 PR was deployed:
- Remove `{{shopify.note}}` variable in Shopify Update Order Notes step.
- Check **Preserve the existing note**.
mesa.json
QA
> Shopify: Update Add customer's orders to order notes template

- shopify/order/add_customers_orders_to_notes/mesa.json
- shopify/order/add_free_product_to_new_customer_first_order/mesa.json
- shopify/order/send_postcard_to_customer_if_first_order/mesa.json
Update 'Add customer's orders to order notes' template https://app.asana.com/0/393037162945950/1204133428228882
mesa.json
QA
Check that these 3 templates work as expected:
> Update templates that reference order_spend

- shopify/product/add_placeholder_image/mesa.json
The Shopify Product Created trigger does not include the product's images. Add the Shopify Retrieve Product step after the Shopify Product Created trigger.
Also updated the Filter step to use the "is not empty" condition.
[Asana Ticket](https://app.asana.com/0/393037162945950/1204171561462356/f)
mesa.json
QA
> Update Add a placeholder image when a Shopify product is created template

- shopify/product/automatically_publish/mesa.json
The Shopify Product Created trigger does not include the product's images. Add the Shopify Retrieve Product step after the Shopify Product Created trigger.
[Asana Ticket](https://app.asana.com/0/393037162945950/1204171561462356/f)
mesa.json
QA
> Update Automatically publish a product if it has an image and description template

- shopify/product/send_email_when_product_goes_out_of_stock/mesa.json
The `{{shopify_variant.product_id}}` had an unnecessary space which will be removed.
Update the Shopify admin link to the admin.shopify.com link.
mesa.json
QA
> Fix variable in the Receive an email when a product goes out of stock template

- tracktor/fulfillment/send_thanksio_postcard_when_order_delivered/mesa.json
Asana Task: [Update: Send a postcard when an order is delivered](https://app.asana.com/0/1199933048569373/1204172448688883/f)
```
Carrier: Fedex
Tracking#: 394618953660
```
mesa.json
> Add Send a postcard when an order is delivered template

- shopify/order/send_thanksio_postcard_if_first_order/mesa.json
Asana Task: [Update: Send a postcard when a customer places their first order](https://app.asana.com/0/1199933048569373/1204171561462344/f)
mesa.json
> Add Send a postcard when a customer places their first order template

- infiniteoptions/order/send_email/mesa.json
- shopify/customer/tag_customers_with_edu_email/mesa.json
- shopify/customer/tag_vip_customers/mesa.json
- shopify/draft_order/remove_after_thirty_days/mesa.json
- shopify/order/add_customers_orders_to_notes/mesa.json
- shopify/order/add_payment_gateway_tag/mesa.json
- shopify/order/add_product_tag/mesa.json
- shopify/order/cancel_high_risk_orders/mesa.json
- shopify/order/receive_sms_when_order_created/mesa.json
- shopify/order/send_email_notification_when_order_has_notes/mesa.json
- shopify/order/send_expedited_shipping_alert_to_logistics/mesa.json
- shopify/order/send_high_risk_orders_to_sms/mesa.json
- shopify/order/send_order_report_card_email/mesa.json
- shopify/product/add_color_tag/mesa.json
- shopify/product/automatically_publish/mesa.json
- shopify/product/create_product_descriptions_with_aibymesa/mesa.json
- shopify/product/send_email_when_product_goes_out_of_stock/mesa.json
- shopify/product/update_when_out_of_stock/mesa.json
- tracktor/fulfillment/add_tag_with_current_delivery_status/mesa.json
- tracktor/fulfillment/delay_in_transit_email/mesa.json
- tracktor/fulfillment/delay_in_transit_sms/mesa.json
- tracktor/fulfillment/send_email_when_in_transit/mesa.json
- tracktor/fulfillment/send_sms_when_order_delivered/mesa.json
> Mesa Templates: Add setup: true attribute to all No Setup templates

- shopify/customer/create_discount_code_for_new_customers/mesa.json
Add Filter step to check for phone number.
Replaced Email by MESA with SMS by MESA.
Asana: [Update: 'Create a unique discount code for new customers to apply towards a specific product' template to use SMS instead](https://app.asana.com/0/393037162945950/1204171561462326/f)
mesa.json
> Update template: Create a unique discount code for new customers to apply towards a specific product

- recharge/order/add_order_count_to_order_notes/mesa.json
Asana: [Add customer's Recharge order to order notes](https://app.asana.com/0/1199933048569373/1204342340814559/f)
mesa.json
> Add template: Add a customer's Recharge order count to order notes

- infiniteoptions/order/send_email/mesa.json
- shopify/draft_order/send_email_notification/mesa.json
- shopify/order/create_shipping_label_and_post_to_slack/custom.js
- shopify/order/create_shipping_label_and_post_to_slack/mesa.json
- shopify/order/send_expedited_shipping_alert_to_logistics/mesa.json
- shopify/product/send_email_when_product_goes_out_of_stock/mesa.json
Removing template variables from Email's Body/Subject Line fields and adding the "Automatically create a Shopify order's shipping label and post it to Slack" template
Asana Tasks
- https://app.asana.com/0/1199933048569373/1204585658619762/f
- https://app.asana.com/0/1199933048569373/1204583491650287/f
mesa.json
> Remove template variables from Email & Add '...create a Shopify order's shipping label' template

- infiniteoptions/order/update_tracktor_status/README.md
- infiniteoptions/order/update_tracktor_status/mesa.json
- tracktor/fulfillment/delay_in_transit_twilio_sms/mesa.json
- tracktor/fulfillment/email_when_package_takes_too_long/mesa.json
- tracktor/fulfillment/send_thanksio_postcard_when_order_delivered/mesa.json
- tracktor/fulfillment/send_to_delighted_nps_survey/mesa.json
- tracktor/fulfillment/send_to_stampedio_review_request/mesa.json
- tracktor/fulfillment/send_twilio_sms_when_order_delivered/mesa.json
- tracktor/order/update_status_shipping_method/mesa.json
- uploadery/order/send_email/README.md
- uploadery/order/send_email/mesa.json
- uploadery/order/send_file_to_dropbox/README.md
- uploadery/order/send_file_to_dropbox/mesa.json
Templates:
- Update Tracktor status when an order has been customized with Infinite Options
- Receive a text message if an order is delayed in transit
- Send an email if a package hasn't been delivered
- Send a postcard when an order is delivered
- Send a NPS survey to a customer after their order is delivered
- Send a review request after an order has been delivered
- Send your customer an SMS message when their order is delivered
- Update an order's status and send an email if Express shipping is enabled
- Send an email when an Uploadery order is created
- Send Uploadery files to Dropbox
mesa.json
> Add template setup round 2

- infiniteoptions/order/send_discord_invite_via_email/mesa.json
- infiniteoptions/order/send_discord_message/README.md
- infiniteoptions/order/send_discord_message/mesa.json
- infiniteoptions/order/send_slack_notification/mesa.json
- tracktor/fulfillment/automatically_set_custom_status/mesa.json
- tracktor/fulfillment/send_track_to_segment/mesa.json
Templates:
- Email a Discord invitation when a product using Infinite Options is purchased
- Delay custom order status updates
- Send a Tracktor fulfillment status update to Segment
- Send a Slack notification when a product with options is purchased
- Send a Discord message when a product using infinite options is purchased
mesa.json
> Add template setup round 3

- tracktor/fulfillment/automatically_set_custom_status/mesa.json
Template: Delay custom order status updates
mesa.json
> Fix template setup

- uploadery/order/add_line_items_to_google_sheet/mesa.json
> Uploadery: Add template onboarding support

- gorgias/ticket/send_gift_card_when_order_delayed/mesa.json
- shopify/draft_order/remove_after_thirty_days/mesa.json
- shopify/order/lock_editing_with_tags/mesa.json
- shopify/order/send_email_to_loyaltylion_customer_if_rewards_not_used/mesa.json
- shopify/order/send_gift_card_for_orders_over_100/mesa.json
- shopify/order/send_thanks_io_postcard/mesa.json
- shopify/order/send_to_delighted_nps_survey/mesa.json
- shopify/product/add_and_remove_tags_on_new_products/mesa.json
- stamped_io/review/send_negative_review_to_customer_email/mesa.json
- tracktor/fulfillment/automatically_set_custom_status/mesa.json
- tracktor/fulfillment/delay_in_transit_email/mesa.json
- tracktor/fulfillment/delay_in_transit_sms/mesa.json
- tracktor/fulfillment/delay_in_transit_twilio_sms/mesa.json
- tracktor/fulfillment/email_when_package_takes_too_long/mesa.json
- tracktor/fulfillment/send_to_delighted_nps_survey/mesa.json
- tracktor/fulfillment/send_to_stampedio_review_request/mesa.json
- tracktor/order/refund_shipping_cost/mesa.json
To be deployed with https://github.com/shoppad/ShopPad/pull/8930
mesa.json
> Delay v2 launch: specify version as v1

- shopify/order/tag_customer_when_specific_product_purchased/mesa.json
- [MESA Templates Asana Task](https://app.asana.com/0/1199933048569373/1204498444352936/f)
mesa.json
> Add template: Tag a customer when they purchase a specific product

- shopify/order/add_free_product_to_new_customer_first_order/mesa.json
> Set Notify Customer field to false for template: Add a free product to a new customer's first Shopify order

- shopify/product/add_to_etsy_listing/mesa.json
> Fix template setup: Add a listing on Etsy when a new product is created in Shopify

- shopify/order/send_file_to_dropbox/mesa.json
[MESA Templates Asana Task](https://app.asana.com/0/1199933048569373/1205167970689641/f)
mesa.json
> Add template setup: Send files from a Shopify order to Dropbox

- shopify/order/send_discord_message_when_tagged/mesa.json
- shopify/order/tag_customer_when_specific_product_purchased/mesa.json
- shopify/product/update_when_out_of_stock/mesa.json
- uploadery/order/add_line_items_to_google_sheet/mesa.json
> Loop v2: Add version to 4 missing templates

- shopify/order/add_currency_to_order_tags/mesa.json
- shopify/order/add_fulfillment/mesa.json
- shopify/order/add_shipping_province_tag/mesa.json
- MESA Templates Asana Tasks
- [Wizard: Add fulfillment to line items that don't require shipping](https://app.asana.com/0/1199933048569373/1205452796090548/f)
- [Wizard: Tag a Shopify order with the shipping province or state](https://app.asana.com/0/1199933048569373/1205452796090576/f)
- [Wizard: Add a currency tag to a Shopify order](https://app.asana.com/0/1199933048569373/1205452796090521/f)
mesa.json
> Add template setup to shopify templates

- shopify/order/update_square_inventory/mesa.json
- [MESA Templates Asana Task](https://app.asana.com/0/1199933048569373/1205148395741495/f)
mesa.json
> Add template: Update inventory in Square when a Shopify order is created

- shopify_pos/order/tag_pos_orders /mesa.json
- shopify_pos/order/tag_pos_orders/mesa.json
- [MESA Templates Asana Task](https://app.asana.com/0/1199933048569373/1205735863152349/f)
mesa.json
> Add template: Tag Shopify POS orders

- shopify/order/add_task_to_asana/mesa.json
- MESA Templates Asana Task: [Wizard: Update 'Add a task in Asana when a Shopify order is created'](https://app.asana.com/0/1199933048569373/1205131768983838/f)
mesa.json
> Add template setup: Add a task in Asana when a Shopify order is created

- shopify/product/slack_message_when_product_goes_out_of_stock/mesa.json
- Asana Task: [Wizard: Send a Slack message when a product goes out of stock](https://app.asana.com/0/1199933048569373/1205458398219265/f)
mesa.json
> Add template setup: Send a Slack message when a product goes out of stock

- shopify/product/send_slack_message_inventory_low/mesa.json
- Asana Task: [Wizard: Send a Slack message when inventory runs low](https://app.asana.com/0/1199933048569373/1205458398219268/f)
mesa.json
> Add template setup: Send a Slack message when inventory runs low

- shopify/order/send_order_customer_details_to_odoo/mesa.json
- Related Asana Task: https://app.asana.com/0/0/1205903698114101/1205951633972336/f
- Merchant ran into an issue with the Loop step not looping over items.
mesa.json
> Odoo: Set Loop version to v1 for Send Shopify order and customer details to Odoo

- shopify/customer/add_email_to_klaviyo_list/mesa.json
- MESA Templates Asana: [Wizard: Add a Shopify customer's email address to a Klaviyo list](https://app.asana.com/0/1199933048569373/1205452796090462/f)
mesa.json
> Add template setup: Add a Shopify customer's email address to a Klaviyo list

- shopify/order/send_order_paid_message_to_slack/mesa.json
[Wizard: Send a Slack message when a Shopify order is created](https://app.asana.com/0/1199933048569373/1205458398219282/f)
mesa.json
> Add template setup: Send a Slack message when a Shopify order is created

- shopify/order/send_international_orders_to_slack/mesa.json
[Wizard: Send a Slack message when an international order is created in Shopify](https://app.asana.com/0/1199933048569373/1205458399111858/f)
mesa.json
> Add template setup: Send a Slack message when an international order is created in Shopify

- shopify/customer/add_email_to_klaviyo_list/mesa.json
- shopify/customer/backorder_tag_to_klaviyo_email_list/mesa.json
- shopify/order/subscribe_shoppers_to_klaviyo_list/mesa.json
Klaviyo app was deployed with a new version mentioned by Darryl in [#announcements](https://shoppad.slack.com/archives/C066XCUN4/p1699484412953049).
Templates that need to be updated.
- [Add a Shopify customer's email address to a Klaviyo list](https://app.getmesa.com/install/shopify/customer/add_email_to_klaviyo_list)
- [Subscribe shoppers to a Klaviyo list after their first order](https://app.getmesa.com/install/shopify/order/subscribe_shoppers_to_klaviyo_list)
- [Add a customer with a backorder tag to a Klaviyo email list](https://app.getmesa.com/install/shopify/customer/backorder_tag_to_klaviyo_email_list)
Add a Shopify customer's email address to a Klaviyo list
Subscribe shoppers to a Klaviyo list after their first order
Add a customer with a backorder tag to a Klaviyo email list …
> Update Klaviyo Templates

- etsy/order/send_to_google_sheets/mesa.json
- Remove `{{etsy.buyer_email}}` variable due to Etsy API updates.
- Asana: https://app.asana.com/0/0/1206281619187072/1206436189271003/f
mesa.json
> Update template: Send Etsy orders to Google Sheets

- shopify/product/create_a_pin/mesa.json
Add "Shopify Retrieve Product" step after "Shopify Product Created" trigger to fix image URL error.
Asana: [Create a pin when a product is created in Shopify template throwing image URL error](https://app.asana.com/0/393037162945950/1206650072961350/f)
mesa.json
> Fix Create a pin when a product is created in Shopify template

- shopify/order/send_to_airtable/mesa.json
Asana
- [Wizard: Send Shopify orders to Airtable](https://app.asana.com/0/1199933048569373/1205443820484020/f)
mesa.json
> Add template setup wizard to Send Shopify orders to Airtable

- shopify/order/free_product_added_when_specific_product_purchased/mesa.json
- shopify/order/send_email_when_specific_product_purchased/mesa.json
- Asana
- [Add a free product when a specific product is purchased](https://app.asana.com/0/1199933048569373/1205891070435043/f)
-  [Send an email when a specific product is purchased](https://app.asana.com/0/1199933048569373/1205891070435046/f)
2 templates to QA
Add a free product when a specific product is purchased
Send an email when a specific product is purchased
mesa.json
> Shopify: Add templates

- form/customer_dob/README.md
- form/customer_dob/mesa.json
- Asana: [Wizard: Save a customer's birthday to notes](https://app.asana.com/0/1199933048569373/1205458398219257/f)
mesa.json
> Add template setup: Save a customer's birthday to notes

- form/post_purchase_survey/mesa.json
- Asana: [Wizard: Add a post-purchase survey form and send results to Google Sheets](https://app.asana.com/0/1199933048569373/1205452796090432/f)
mesa.json
> Add template setup: Add a post-purchase survey form and send results to Google Sheets

- shopify/order/send_order_customer_details_to_odoo/filter.js
- Issue with Filter's inability to check for multiple line items in a Shopify order
- Escalated by CS: https://app.asana.com/0/1204480351344394/1206944525938150/f
- Issue was resolved with these updates
mesa.json
> Update Filter in Send Shopify order and customer details to Odoo errors template

- shopify/order/send_order_customer_details_to_odoo/mesa.json
- For the first Filter step, change the comparison from "Equals" to "Is in".
- Asana tasks related to this update:
- [ratchetstrap-com: Send Shopify order and customer details to Odoo errors](https://app.asana.com/0/1204480351344394/1207041094573659/f)
- [catastrophic-creations-furniture: Send Shopify order and customer details to Odoo errors](https://app.asana.com/0/1204480351344394/1206944525938150/f)
- Update to new template schema by removing `description`, `video`, etc...
mesa.json
> Update template: Send Shopify order and customer details to Odoo

- shopify/checkout/send_abandoned_carts_to_google_sheets/mesa.json
- Remove the `api_endpoint` from template in order to display the "Spreadsheet" and "Sheet" fields, and "Sync with spreadsheet" button
- #mesa-questions: https://shoppad.slack.com/archives/C02UR4R7N2W/p1713374820167759
mesa.json
> Fix template: Send a list of abandoned carts to Google Sheets

- shopify/product/create_product_descriptions_with_aibymesa/mesa.json
- shopify/product/generate_shopify_product_tags_with_ai_by_mesa/mesa.json
- unsearchable/shopify/order/ai_generated_post_purchase_email/mesa.json
- unsearchable/shopify/order/detect-po-box/mesa.json
- Related PR: https://github.com/shoppad/ShopPad/pull/10047
mesa.json
> Add version to AI by Mesa steps in existing templates

- shopify/product/create_product_descriptions_with_aibymesa/mesa.json
- shopify/product/generate_shopify_product_tags_with_ai_by_mesa/mesa.json
- Updating `Use AI by MESA to write Shopify product descriptions` and `Use AI by MESA to generate Shopify product tags` to v2
- Jen said to ignore unsearchables for now. Will get back to me about it later.
mesa.json
> Update public AI templates to v2

- shopify/order/send_to_airtable/mesa.json
- shopify/product/sync_to_airtable_kj/mesa.json
- unsearchable/shopify/order/update-bundle-inventory/mesa.json
- unsearchable/shopify/product/sync_images_to_airtable/mesa.json
- uploadery/order/add_line_items_to_airtable/mesa.json
> MESA: Updating Airtable templates to V3

- google_sheets/row/create_fulfillment_from_new_row/mesa.json
- Asana: [Create a Shopify order fulfillment from a new row in Google Sheets](https://app.asana.com/0/1199933048569373/1205863970962585/f)
mesa.json
> Add template: Create an order fulfillment from a new row in Google Sheets

- shopify/order/send_orders_to_a_data_table/mesa.json
Asana: [Send Shopify orders to a database](https://app.asana.com/0/562906963533984/1207210468793739/f)
mesa.json
> Add template 'Send Shopify orders to a database'

- shopify/customer/send_customers_to_a_data_table/mesa.json
Asana: [Send Shopify customers to a database](https://app.asana.com/0/562906963533984/1207210469398051/f)
mesa.json
> Add template 'Send Shopify customers to a database'

- shopify/order/send_a_discord_message_when_a_new_order_is_created/mesa.json
Asana: [Send a Discord message when a Shopify order is created](https://app.asana.com/0/562906963533984/1204373034936764/f)
mesa.json
> Add 'Send a Discord message when a Shopify order is created' template

- google_sheets/row/send_gmail_email_from_googlesheets/mesa.json
Asana: [Send an email from a new row in Google Sheets](https://app.asana.com/0/1199933048569373/1207815975164582/f)
mesa.json
> Add 'Send an email from a new row in Google Sheets' template

- shopify/order/send_order_customer_details_to_odoo/mesa.json
- Asana Task: https://app.asana.com/0/770345770753602/1207947323655881/f
mesa.json
> Odoo Template: Remove problematic product_qty field

- shopify/order/schedule_daily_export_of_orders_into_google_sheets/mesa.json
- Replacing legacy steps (Google Drive Create Spreadsheet, GS Create New Sheet) with the latest steps
```
SELECT * FROM "Add table name here" WHERE "Created At" > '{{date:yesterday}}';
```
mesa.json
> Updating Schedule a daily export of orders into Google Sheets template

- shopify/order/send_order_customer_details_to_odoo/mesa.json
- Related PR: https://github.com/shoppad/ShopPad/pull/10031
mesa.json
> Add version to Odoo templates

- shopify/order/flag_order_risk_if_no_price/mesa.json
> Enable template setup: Automatically Flag $0 Orders as Risky in Shopify

- shopify/order/send_to_airtable/mesa.json
- [Airtable: Add support for creating pages from a template wizard step Asana Task](https://app.asana.com/0/770345770753602/1208554813849458/f)
mesa.json
> Add setup wizard to Send Shopify orders to Airtable template

- shopify/order/send_to_a_notion_database/mesa.json
- Mesa template asana task: https://app.asana.com/1/71291173468390/project/1199933048569373/task/1204928240111166?focus=true
- Related SP pr: https://github.com/shoppad/ShopPad/pull/10882
- [Need to add the `custom` attribute for a custom field that doesn't live on a step](https://github.com/shoppad/ShopPad/pull/10882/files#diff-e1d8b100a17d8d23c5c95cda382c21c96f5f5066e0d920891f4ea18d152bad80R428)
```
// Check if field has a "custom" attribute and if it is set to true
elseif (isset($field['custom']) && $field['custom'] === true) {
```
mesa.json
> Add Send Shopify orders to Notion database template

- mcp/slack/send/mesa.json
> Add template: mcp_slack_send

- mcp/retrieve_helpscout_conversations/custom.js
- mcp/retrieve_helpscout_conversations/mesa.json
> Add mcp/retrieve_helpscout_conversations template

- mcp/mantle/retrieve_customers/mesa.json
- mcp/mantle/tag_customer/mesa.json
- mcp/shopifypartners/retrieve_installs/mesa.json
- mcp/shopifypartners/retrieve_subscription_activations/mesa.json
- mcp/shopifypartners/retrieve_uninstalls/mesa.json
- mcp/shopifypartners/retrieve_usage_charges/mesa.json
> Mesa: Add 6 Shopify Partner/Mantle MCP templates

- mcp/autogen/yedric_to_ask_workflow/mesa.json
- mcp/autogen/yedric_to_custom_skill/mesa.json
- yotpoloyalty/customer_points/send_to_omnisend_contact/mesa.json
> Yedric autogen templates for _Run_Prompt_on_a_Schedule, _Create_Custom_Skill tools

- mcp/autogen/yedric_to_custom_skill/mesa.json
> Adding metadata.auto_config to mcp/autogen/yedric_to_custom_skill
